# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cv_builder.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1005, 715)
        MainWindow.setStyleSheet("QPushButton {\n"
"    background-color: #E74C3C;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    border-radius: 6px;\n"
"    padding: 6px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 110, 311, 351))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setStyleSheet("QTabWidget::pane{\n"
"    border: 1px solid #BDC3C7;\n"
"}\n"
"\n"
"QTabBar::tab{\n"
"    background: #ECF0F1;\n"
"    padding: 8px;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:selected{\n"
"    background: #3498DB;\n"
"    color: white;\n"
"}")
        self.tabWidget.setIconSize(QtCore.QSize(30, 20))
        self.tabWidget.setObjectName("tabWidget")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.QLabel = QtWidgets.QLabel(self.widget)
        self.QLabel.setGeometry(QtCore.QRect(20, 10, 71, 21))
        self.QLabel.setObjectName("QLabel")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 51, 21))
        self.label_3.setObjectName("label_3")
        self.lineEdit_name = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_name.setGeometry(QtCore.QRect(20, 40, 191, 16))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.lineEdit_email = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_email.setGeometry(QtCore.QRect(20, 100, 191, 16))
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(20, 130, 91, 21))
        self.label_4.setObjectName("label_4")
        self.lineEdit_phone = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_phone.setGeometry(QtCore.QRect(20, 160, 191, 16))
        self.lineEdit_phone.setObjectName("lineEdit_phone")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(20, 230, 61, 21))
        self.label_5.setObjectName("label_5")
        self.textEdit_address = QtWidgets.QTextEdit(self.widget)
        self.textEdit_address.setGeometry(QtCore.QRect(20, 260, 211, 21))
        self.textEdit_address.setObjectName("textEdit_address")
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setGeometry(QtCore.QRect(20, 190, 41, 21))
        self.label_12.setObjectName("label_12")
        self.lineEdit_cnic = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_cnic.setGeometry(QtCore.QRect(20, 212, 191, 16))
        self.lineEdit_cnic.setObjectName("lineEdit_cnic")
        self.tabWidget.addTab(self.widget, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 111, 41))
        self.label_2.setObjectName("label_2")
        self.textEdit_education = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_education.setGeometry(QtCore.QRect(10, 70, 271, 211))
        self.textEdit_education.setObjectName("textEdit_education")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_7 = QtWidgets.QLabel(self.tab_4)
        self.label_7.setGeometry(QtCore.QRect(20, 20, 61, 31))
        self.label_7.setObjectName("label_7")
        self.textEdit_skills = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_skills.setGeometry(QtCore.QRect(20, 60, 251, 311))
        self.textEdit_skills.setObjectName("textEdit_skills")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 81, 31))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(20, 20, 71, 31))
        self.label_8.setObjectName("label_8")
        self.textEditexperience = QtWidgets.QTextEdit(self.tab_3)
        self.textEditexperience.setGeometry(QtCore.QRect(20, 60, 251, 231))
        self.textEditexperience.setObjectName("textEditexperience")
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(180, 689, 631, 101))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(20, 470, 141, 41))
        self.btn_save.setStyleSheet("QPushButton{\n"
"    background-color: #27AE60;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    border-radius: 6px;\n"
"    padding: 6px;\n"
"}")
        self.btn_save.setObjectName("btn_save")
        self.btn_load = QtWidgets.QPushButton(self.centralwidget)
        self.btn_load.setGeometry(QtCore.QRect(20, 520, 141, 41))
        self.btn_load.setStyleSheet("QPushButton{\n"
"    background-color: #3498DB;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    border-radius: 6px;\n"
"    padding: 6px;\n"
"}")
        self.btn_load.setObjectName("btn_load")
        self.btn_export = QtWidgets.QPushButton(self.centralwidget)
        self.btn_export.setGeometry(QtCore.QRect(20, 570, 141, 41))
        self.btn_export.setStyleSheet("QPushButton{\n"
"    background-color: #E67E22;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    border-radius: 6px;\n"
"    padding: 6px;\n"
"}")
        self.btn_export.setObjectName("btn_export")
        self.textBrowser_preview = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_preview.setGeometry(QtCore.QRect(355, 141, 631, 521))
        self.textBrowser_preview.setStyleSheet("QTextBrowser{\n"
"    background-color: white;\n"
"    border: 2px solid #BDC3C7;\n"
"    padding: 10px;\n"
"    font-family: Segoe UI;\n"
"    font-size: 10pt;\n"
"}")
        self.textBrowser_preview.setObjectName("textBrowser_preview")
        self.btn_clear = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear.setGeometry(QtCore.QRect(20, 620, 141, 31))
        self.btn_clear.setStyleSheet("QPushButton {\n"
"    background-color: #E74C3C;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    border-radius: 6px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.btn_clear.setObjectName("btn_clear")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(360, 110, 607, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("QTextBrowser{\n"
"    background-color: white;\n"
"    border: 2px solid #BDC3C7;\n"
"    padding: 10px;\n"
"    font-family: Segoe UI;\n"
"    font-size: 10pt;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 0, 981, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel{\n"
"    background-color: #2C3E50;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"}")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 59, 971, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setItalic(True)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(240, 570, 101, 41))
        self.label_11.setStyleSheet("QLabel{\n"
"    color: #2C3E50;\n"
"    font-size: 10pt;\n"
"    font-weight: bold;\n"
"}")
        self.label_11.setObjectName("label_11")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(240, 610, 101, 31))
        self.comboBox.setStyleSheet("QComboBox{\n"
"    background-color: #3498DB;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    border-radius: 6px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView{\n"
"    background-color: white;\n"
"    color: black;\n"
"    selection-background-color: #3498DB;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.btn_photo = QtWidgets.QPushButton(self.centralwidget)
        self.btn_photo.setGeometry(QtCore.QRect(230, 470, 101, 31))
        self.btn_photo.setStyleSheet("QPushButton { \n"
"    background-color: #C19A6B; \n"
"    color: white; \n"
"    font-weight: bold; \n"
"    border-radius: 6px; \n"
"    padding: 6px; \n"
"}")
        self.btn_photo.setObjectName("btn_photo")
        self.label_photo = QtWidgets.QLabel(self.centralwidget)
        self.label_photo.setGeometry(QtCore.QRect(850, 160, 120, 120))
        self.label_photo.setStyleSheet("QLabel{\n"
"    border: 2px solid gray;\n"
"    background-color: white;\n"
"}")
        self.label_photo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_photo.setObjectName("label_photo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1005, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.QLabel.setText(_translate("MainWindow", "Full Name"))
        self.label_3.setText(_translate("MainWindow", "Email"))
        self.label_4.setText(_translate("MainWindow", "Phone Number"))
        self.label_5.setText(_translate("MainWindow", "Address"))
        self.label_12.setText(_translate("MainWindow", "CNIC"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("MainWindow", "Personal Info"))
        self.label_2.setText(_translate("MainWindow", "Educational Details"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Education"))
        self.label_7.setText(_translate("MainWindow", "Skills"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Skills"))
        self.label_8.setText(_translate("MainWindow", "Experience"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Experience"))
        self.btn_save.setText(_translate("MainWindow", "💾 Save"))
        self.btn_load.setText(_translate("MainWindow", "📂 Load"))
        self.btn_export.setText(_translate("MainWindow", "📄 Export PDF"))
        self.btn_clear.setText(_translate("MainWindow", "🗑 Clear"))
        self.label.setText(_translate("MainWindow", "Live CV Preview"))
        self.label_9.setText(_translate("MainWindow", "RESUME BUILDER PRO"))
        self.label_10.setText(_translate("MainWindow", "Create Professional CVs Easily"))
        self.label_11.setText(_translate("MainWindow", "TEMPLATE:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "CLASSIC"))
        self.comboBox.setItemText(1, _translate("MainWindow", "MODERN"))
        self.btn_photo.setText(_translate("MainWindow", "Upload Photo"))
        self.label_photo.setText(_translate("MainWindow", "Photo"))
